### ISSUE TITLE
Concept error about wifi and mobile data

### ISSUE THREAD

**Issue by pedris11s** [todo-devs/todo_v1#13]
![Screenshot_2020-06-26-00-17-29-519_com cubanopensource todo](https://user-images.githubusercontent.com/48369986/85819726-97c1b380-b742-11ea-9d95-7d99b5c52592.jpg)

Im connected by mobile data, why the app says that i have a wifi connection with etecsa? Is not the same. Thanks in advance, good idea with the project!!!

**Comment by luiscib3r** [comment]
Gracias por el issue, preferimos responder en español ya que la app esta destinada a usuarios cubanos. La app detecta que hay una conexión sin importar por cual vía sea para evitar mostrar el formulario de autenticación al portal cautivo innecesariamente. Hasta el momento no hemos visto la necesidad de diferenciar entre si esta conectado vía wifi o vía datos móviles. Para una próxima actualización tal vez podamos hacer una distinción y mostrar un icono diferente para diferenciar el tipo de conexión.

**Comment by pedris11s** [comment]
Gracias por responder...creo que seria lo ideal en proximos releases. Cierro el issue.
