### ISSUE TITLE
Añadir burbuja flotante con la velocidad de conexión

### ISSUE THREAD

**Issue by groig** [todo-devs/todo_v1#35]

**Comment by nilsandrey** [comment]
Sugiero que el hecho de que la burbuja salga o no salga sea opcional/configurable. Algunos tenemos la velocidad en el status dado por el propio sistema.

**Comment by luiscib3r** [comment]
Hecho en la versión 1.2.4, falta que sea configurable en los ajustes de la aplicación.

**Comment by nilsandrey** [comment]
¿Considerarían como parte de este mismo issue tener la cantidad de horas restantes de nauta hogar como parte del texto flotante? Quizá seleccionar entre uno u otro para que el texto no sea tanto si fuera molesto. Es la misma info que se muestra en pantalla "Conectado".

![image](https://user-images.githubusercontent.com/3579285/87845398-defc1980-c894-11ea-9139-045823b27d96.png)

**Comment by luiscib3r** [comment]
Trabajar en que la burbuja flotante además del tráfico de red también muestre el tiempo restante en caso de estar conectado con una cuenta Nauta

**Comment by luiscib3r** [comment]
El tráfico de red sólo se debe mostrar cuando exista una conexión activa ya sea por WiFi o por datos móviles.

**Comment by luiscib3r** [comment]
> El tráfico de red sólo se debe mostrar cuando exista una conexión activa ya sea por WiFi o por datos móviles.

Resuelto en la versión 1.2.5

**Comment by luiscib3r** [comment]
> Sugiero que el hecho de que la burbuja salga o no salga sea opcional/configurable. Algunos tenemos la velocidad en el status dado por el propio sistema.

Resuelto en la versión 1.2.6
