### ISSUE TITLE
Mejorar la accesibilidad en la página de configuración

### ISSUE THREAD

**Issue by groig** [todo-devs/todo_v1#50]
Parece que TalkBack ve todos los elementos como uno solo y no los lee correctamente

![photo_2020-07-05_12-56-23](https://user-images.githubusercontent.com/15933135/86537738-60c86c00-bebf-11ea-8fda-b7365fc2b195.jpg)

**Comment by luiscib3r** [comment]
No se han reportado más problemas con respecto a a este issue después de la últimas actualizaciones, se cierra el issue.
