### ISSUE TITLE
Categorías no se diferencian

### ISSUE THREAD

**Issue by nilsandrey** [todo-devs/todo_v1#56]
Los elementos de menú que son categorías, no se diferencias de los que ejecutan directamente USSD, puede ser interesante pensar en que se diferencien visualmente para que el usuario lo tenga más claro a la hora de ir navegando por la interfaz, a veces tengo que leer más de una vez para asegurarme, si bien los iconos y demás ayudan podría valorarse variantes.

**Comment by luiscib3r** [comment]
Resuelto en la versión 1.2.5
